config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 	root "grams#index"
 	# resources :grams, only: [:new, :create, :show, :edit, :update, :destroy]
 	resources :grams do
    resources :comments, only: :create
  end
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :message, presence: true
  
  belongs_to :user
  belongs_to :gram
end

app/models/gram.rb
class Gram < ApplicationRecord
	validates :message, presence: true
	validates :image, presence: true

	mount_uploader :image, ImageUploader

	belongs_to 	:user 
  has_many 		:comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :grams
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, only: [:create]

	def create

		@gram = Gram.find_by_id(params[:gram_id])
		return render_not_found if @gram.blank?
		@gram.comments.create(comment_params.merge(user: current_user))

		# Comment.create(comment_params.merge(:user => current_user, :gram_id => params[:gram_id])

		# @gram = Gram.find_by_id(params[:gram_id])
		# @gram.comments.new(comment_params)
		# @gram.user = current_user
		# @gram.save

		redirect_to root_path
	end

	private

  helper_method :current_gram
  def current_gram
    @current_gram ||= Gram.find_by_id(params[:gram_id])
  end

  helper_method :current_comment
  def current_comment
    @current_comment ||= Comment.find_by_id(params[:id])
  end

	def comment_params
		params.require(:comment).permit(:message)
	end

end

app/controllers/grams_controller.rb
class GramsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destory]

	def index
		@grams = Gram.all
	end

	def new
		@gram = Gram.new
	end

	def create
	  @gram = current_user.grams.create(gram_params)
	  if @gram.valid?
	    redirect_to root_path
	  else
	    render :new, status: :unprocessable_entity
	  end
	end

	def destroy
		@gram = Gram.find_by_id(params[:id])	
    return render_not_found if @gram.blank?
		if @gram.user != current_user
			# redirect_to edit_gram_path(@gram), alert: 'Only the author can delete this gram.'
	    return render_not_found(:forbidden)
		else
			@gram.delete
			redirect_to root_path
		end
	end

	def edit
		@gram = Gram.find_by_id(params[:id])
		return render_not_found if @gram.blank?		
		if @gram.user != current_user
			# redirect_to root_path, alert: 'Only the author can edit this gram.'
			return render_not_found(:forbidden)
		end
	end

	def update
		@gram = Gram.find_by_id(params[:id])
		return render_not_found if @gram.blank?
	  return render_not_found(:forbidden) if @gram.user != current_user
		@gram.update_attributes(gram_params)
		if @gram.valid?
	 		redirect_to root_path
	  else
	    return render :edit, status: :unprocessable_entity
	  end
	end

	def show
		@gram = Gram.find_by_id(params[:id])
		render_not_found if @gram.blank?
	end


  private

  helper_method :current_gram
  def current_gram
    @current_gram ||= Gram.find_by_id(params[:id])
  end

  def gram_params
    params.require(:gram).permit(:message, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
  <h2>Edit Gram</h2>

  <%= simple_form_for @gram do |f| %>
    <%= f.input :message %>
    <%= f.input :image %>
    <%= f.submit 'Update', class: 'my-btn' %>
  <% end %>

</div>

app/views/grams/index.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
  <% @grams.each do |gram| %>
  <div class="card">
    <div class="handle"><%= gram.user.email %></div>
    <%= image_tag gram.image, class: 'img-fluid' %>
    <p>
      <%= gram.message %>
    </p>

    <div class="gram-actions float-right">
      <% if current_user && current_user == gram.user %>
        <%= link_to 'Edit', edit_gram_path(gram) %>
        <%= link_to 'Destroy', gram_path(gram), method: :delete, data: {confirm: 'Are you sure?'} %>

      <% end %>
    </div>
    <br class="clear-fix" />
    <div class="comments">
      <h3>Comments</h3>
      <% gram.comments.each do |comment| %>
        <div class="comment">
          <span class="comment_handle">
            <%= comment.user.email %>
          </span>

          <%= comment.message %>
        </div>
      <% end %>
      <h4>Add a comment</h4>
      <%= simple_form_for Comment.new, url: gram_comments_path(gram) do |f| %>
        <%= f.input :message %>
        <%= f.submit 'Add Comment', class: 'my-btn' %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/grams/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">

	<h1>New Gram</h1>

	<%= simple_form_for @gram do |f| %>
	  <%= f.input :message %>
	  <%= f.input :image %>
    <%= f.submit "Post!", class: 'my-btn' %>
	<% end %>

</div>

app/views/grams/show.html.erb
  <h1><%= @gram.inspect %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grammable</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>

	  <div class="top-nav">
	    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
	      <div class="brand float-left">
	        Grammable
	      </div>
	      <div class="add float-right">
	        <% if current_user %>
        		<%= link_to "New Post", new_gram_path %>
	          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
	        <% else %>
	          <%= link_to "Sign In", new_user_session_path %>
	          <%= link_to "Sign Up", new_user_registration_path %>
	        <% end %>
	      </div>
	    </div>
	    <br class="clear-fix" />
	  </div>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grammable</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	  <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
	    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <%= link_to 'Grams', root_path, class: 'navbar-brand' %>

	    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
	      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
	        <li class="nav-item">
	          <%= link_to new_gram_path, class: 'nav-link' do %>
	            <i class="fa fa-plus-circle"></i>
	            New Gram
	          <% end %>
	        </li>
	      </ul>
	      <ul class="navbar-nav">
	        <% if user_signed_in? %>
	          <li class="nav-item">
	            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
	          </li>
	        <% else %>
	          <li class="nav-item">
	            <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
	          </li>
	          <li class="nav-item">
	            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
	          </li>
	        <% end %>
	      </ul>
	    </div>
	  </nav>

<!-- 	  <% if current_user %>
	  You're signed in as <%= current_user.email %>.
	  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
	  <% else %>
	  <%= link_to "Sign In", new_user_session_path %>
	  <%= link_to "Sign Up", new_user_registration_path %>
	  <% end %> -->

		<% if notice.present? %>
		  <p class="alert alert-info"><%= notice %></p>
		<% end %>
		<% if alert.present? %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>

    <%= yield %>
    
  </body>
</html>